apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-homepage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-homepage
        configMap:
          name: nginx-homepage-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-homepage-config
  labels:
    app: nginx
  namespace: default

data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome I.CAS-DEVOPS2024</title>
    </head>
    <body>
        <h1>Welcome to the Custom Nginx Homepage!</h1>
        <p>Deployed with ArgoCD</p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 32488
  type: NodePort
